### ISSUE TITLE
Bug:After Update the newest Playwright version  (1.44.1) got an typeError

### ISSUE THREAD

**Issue by ibektas** [vitalets/playwright-bdd#162]
npx bddgen is working with the Playwright version 1.35.1
after updated the Playwright version to 1.44.1 
i got this stracktrace after i run : npx bddgen

return resolveConfigFile(configFileOrDirectory) || '';
           ^
TypeError: resolveConfigFile is not a function
    at resolveConfigFile (C:\Users\------\Documents\------\node_modules\playwright-bdd\dist\playwright\loadConfig.js:26:12)
    at loadConfig (C:\Users\------\Documents\------\node_modules\playwright-bdd\dist\playwright\loadConfig.js:17:32)
    at Command.<anonymous> (C:\Users\------\Documents\------\node_modules\playwright-bdd\dist\cli\commands\test.js:24:39)
    at Command.listener [as _actionHandler] (C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:494:17)
    at C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1296:65
    at Command._chainOrCall (C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1193:12)
    at Command._parseCommand (C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1296:27)
    at C:\Users\------\Documents\git azure\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1082:27
    at Command._chainOrCall (C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1193:12)
    at Command._dispatchSubcommand (C:\Users\------\Documents\------\node_modules\playwright-bdd\node_modules\commander\lib\command.js:1078:25)

setup is same just the PW version is differ. After downgraded the PW version i did not have any problem.

**Comment by vitalets** [comment]
Can't reproduce. Looks like caching issue.
Could you try to cleanup node_modules and re-install from scratch?
If bug still exists, please provide a demo using https://github.com/vitalets/playwright-bdd-example template.

**Comment by vitalets** [comment]
Closing as there is no reply from author.
